name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.16.3]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
      env:
        CI: true

    - name: Deploy to Heroku
      env:
        HEROKU_TOKEN: ${{ secrets.HEROKU_TOKEN }}
        HEROKU_APP_NAME: 'stormy-ravine-95122'
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      run: git push https://heroku:$HEROKU_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/master:master
